config/routes.rb
Rails.application.routes.draw do
  get 'monitor/dashboard'
  resources :sensors
  resources :readings
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reading.rb
class Reading < ApplicationRecord
end

app/models/sensor.rb
class Sensor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/monitor_controller.rb
class MonitorController < ApplicationController
  def dashboard
    @current_readings={}
    Sensor.all.ids.each do |senor_id|
      @current_readings[senor_id]= Reading.where(sensor_id:senor_id).order(updated_at: :desc).limit(2)
    end
    @sensors = Sensor.all
  end
end

app/controllers/readings_controller.rb
class ReadingsController < ApplicationController
  before_action :set_reading, only: %i[ show edit update destroy ]

  # GET /readings or /readings.json
  def index
    @readings = Reading.all
  end

  # GET /readings/1 or /readings/1.json
  def show
  end

  # GET /readings/new
  def new
    @reading = Reading.new
  end

  # GET /readings/1/edit
  def edit
  end

  # POST /readings or /readings.json
  def create
    @reading = Reading.new(reading_params)

    respond_to do |format|
      if @reading.save
        format.html { redirect_to reading_url(@reading), notice: "Reading was successfully created." }
        format.json { render :show, status: :created, location: @reading }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readings/1 or /readings/1.json
  def update
    respond_to do |format|
      if @reading.update(reading_params)
        format.html { redirect_to reading_url(@reading), notice: "Reading was successfully updated." }
        format.json { render :show, status: :ok, location: @reading }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1 or /readings/1.json
  def destroy
    @reading.destroy

    respond_to do |format|
      format.html { redirect_to readings_url, notice: "Reading was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reading
      @reading = Reading.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reading_params
      params.require(:reading).permit(:sensor_id, :value)
    end
end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: %i[ show edit update destroy ]

  # GET /sensors or /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1 or /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors or /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to sensor_url(@sensor), notice: "Sensor was successfully created." }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1 or /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to sensor_url(@sensor), notice: "Sensor was successfully updated." }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1 or /sensors/1.json
  def destroy
    @sensor.destroy

    respond_to do |format|
      format.html { redirect_to sensors_url, notice: "Sensor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sensor_params
      params.require(:sensor).permit(:name, :input_type, :min_value, :max_value, :minute_between_reading)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monitor_helper.rb
module MonitorHelper
end

app/helpers/readings_helper.rb
module ReadingsHelper
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SapMonitor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monitor/_sensor_widget.html.erb
<div id="Sensor<%=sensor.id%>">
  <strong> Sensor:  <%= sensor.name %> </strong>
  Min:  <%= sensor.min_value %>
  Max:  <%= sensor.max_value %>
  <% if readings.size == 0  %>
    <p> No reading for this sensor!! </p>
  <% else %>
    Current:  <%= readings[0].value %>
     <%= readings[0].updated_at %>
    
    <p>History:  <%= readings.each %> </p>
  <% end  %>
  <p>

</div>

app/views/monitor/dashboard.html.erb
<h1>Dashboard</h1>

<% @sensors.each do |sensor| %>
<%= render "sensor_widget", sensor: sensor, readings: @current_readings[sensor.id]  %>
<% end %>

app/views/readings/_form.html.erb
<%= form_with(model: reading) do |form| %>
  <% if reading.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
        <% reading.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :sensor_id, style: "display: block" %>
    <%= form.number_field :sensor_id %>
  </div>

  <div>
    <%= form.label :value, style: "display: block" %>
    <%= form.text_field :value %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/readings/_reading.html.erb
<div id="<%= dom_id reading %>">
  <p>
    <strong>Sensor:</strong>
    <%= reading.sensor_id %>
  </p>

  <p>
    <strong>Value:</strong>
    <%= reading.value %>
  </p>

</div>

app/views/readings/edit.html.erb
<h1>Editing reading</h1>

<%= render "form", reading: @reading %>

<br>

<div>
  <%= link_to "Show this reading", @reading %> |
  <%= link_to "Back to readings", readings_path %>
</div>

app/views/readings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Readings</h1>

<div id="readings">
  <% @readings.each do |reading| %>
    <%= render reading %>
    <p>
      <%= link_to "Show this reading", reading %>
    </p>
  <% end %>
</div>

<%= link_to "New reading", new_reading_path %>

app/views/readings/new.html.erb
<h1>New reading</h1>

<%= render "form", reading: @reading %>

<br>

<div>
  <%= link_to "Back to readings", readings_path %>
</div>

app/views/readings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @reading %>

<div>
  <%= link_to "Edit this reading", edit_reading_path(@reading) %> |
  <%= link_to "Back to readings", readings_path %>

  <%= button_to "Destroy this reading", @reading, method: :delete %>
</div>

app/views/sensors/_form.html.erb
<%= form_with(model: sensor) do |form| %>
  <% if sensor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
        <% sensor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :input_type, style: "display: block" %>
    <%= form.text_field :input_type %>
  </div>

  <div>
    <%= form.label :min_value, style: "display: block" %>
    <%= form.text_field :min_value %>
  </div>

  <div>
    <%= form.label :max_value, style: "display: block" %>
    <%= form.text_field :max_value %>
  </div>

  <div>
    <%= form.label :minute_between_reading, style: "display: block" %>
    <%= form.number_field :minute_between_reading %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sensors/_sensor.html.erb
<div id="<%= dom_id sensor %>">
  <p>
    <strong>Name:</strong>
    <%= sensor.name %>
  </p>

  <p>
    <strong>Input type:</strong>
    <%= sensor.input_type %>
  </p>

  <p>
    <strong>Min value:</strong>
    <%= sensor.min_value %>
  </p>

  <p>
    <strong>Max value:</strong>
    <%= sensor.max_value %>
  </p>

  <p>
    <strong>Minute between reading:</strong>
    <%= sensor.minute_between_reading %>
  </p>

</div>

app/views/sensors/edit.html.erb
<h1>Editing sensor</h1>

<%= render "form", sensor: @sensor %>

<br>

<div>
  <%= link_to "Show this sensor", @sensor %> |
  <%= link_to "Back to sensors", sensors_path %>
</div>

app/views/sensors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sensors</h1>

<div id="sensors">
  <% @sensors.each do |sensor| %>
    <%= render sensor %>
    <p>
      <%= link_to "Show this sensor", sensor %>
    </p>
  <% end %>
</div>

<%= link_to "New sensor", new_sensor_path %>

app/views/sensors/new.html.erb
<h1>New sensor</h1>

<%= render "form", sensor: @sensor %>

<br>

<div>
  <%= link_to "Back to sensors", sensors_path %>
</div>

app/views/sensors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sensor %>

<div>
  <%= link_to "Edit this sensor", edit_sensor_path(@sensor) %> |
  <%= link_to "Back to sensors", sensors_path %>

  <%= button_to "Destroy this sensor", @sensor, method: :delete %>
</div>